from pathlib import Path

IS_DEBUG = False
FPS = 60
ROWS_OF_BLOCKS = 6
BLOCKS_IN_ROW = 13

BASE_DIR = Path(__file__).resolve().parent
ASSETS_DIR = BASE_DIR / 'assets'
SOUNDS_DIR = ASSETS_DIR / 'sounds'
FONTS_DIR = ASSETS_DIR / 'fonts'

MENU_FONT = FONTS_DIR / 'PressStart2P-Regular.ttf'
HUD_FONT = FONTS_DIR / 'PressStart2P-Regular.ttf'

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREY = (157, 157, 157)
YELLOW = (255, 255, 0)
RED = (255, 0, 0)
BLUE = (0, 112, 255)
MAGENTA = (255, 0, 255)
GREEN = (0, 255, 0)
PINK = (255, 20, 147)

BLOCK_COLORS = (
    GREY,
    RED,
    YELLOW,
    BLUE,
    MAGENTA,
    GREEN,
)

MENU_COLOR = WHITE
HUD_COLOR = WHITE
BALL_COLOR = WHITE
RACKETS_COLOR = WHITE
BONUS_BLOCK_COLOR = RED
DROP_COLOR = PINK
